on: [push, pull_request]

name: ci

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --examples --verbose
    - name: Run tests
      run: cargo test --doc --verbose
